---
driver_plugin: vagrant
platforms: 
- name: ubuntu-12.04
  driver_config:
    box: ubuntu-12.04
    box_url: https://mopub-virtual-machines.s3.amazonaws.com/ubuntu-12.04.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
suites:
- name: graphite_runit
  run_list: 
  - recipe[graphite::test_graphite]
  attributes: {}
- name: carbonplusgraphite_runit
  run_list: 
  - recipe[graphite::test_carbonplus_graphite]
  attributes: {}
- name: example
  run_list:
  - recipe[graphite::example]

